### ISSUE TITLE
Cannot Compile: Token/ErrorToken

### ISSUE THREAD

**Issue by jpjpjp4747** [christopherpoole/CADMesh#24]
I am getting this error message and failing to compile. I read a previous post that said to compile using 1.1 instead of from the master branch, which I have done ensuring to checkout v1.1, yet I still get the following error message upon compiling.

`Scanning dependencies of target cadmesh
[ 48%] Building CXX object CMakeFiles/cadmesh.dir/src/BuiltInReader.cc.o
In file included from /nfs/erl/online/user/jgp98/CADMesh/include/BuiltInReader.hh:5:0,
                 from /nfs/erl/online/user/jgp98/CADMesh/src/BuiltInReader.cc:3:
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:34:37: error: no matching function for call to âCADMesh::File::Token::Token(<brace-enclosed initializer list>)â
 static Token ErrorToken{"ErrorToken"};
                                     ^
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note: candidate: constexpr CADMesh::File::Token::Token()
 struct Token 
        ^
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note:   candidate expects 0 arguments, 1 provided
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note: candidate: CADMesh::File::Token::Token(const CADMesh::File::Token&)
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note:   no known conversion for argument 1 from âconst char [11]â to âconst CADMesh::File::Token&â
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note: candidate: CADMesh::File::Token::Token(CADMesh::File::Token&&)
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note:   no known conversion for argument 1 from âconst char [11]â to âCADMesh::File::Token&&â
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:35:45: error: no matching function for call to âCADMesh::File::Token::Token(<brace-enclosed initializer list>)â
 static Token EndOfFileToken{"EndOfFileToken"};
                                             ^
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note: candidate: constexpr CADMesh::File::Token::Token()
 struct Token 
        ^
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note:   candidate expects 0 arguments, 1 provided
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note: candidate: CADMesh::File::Token::Token(const CADMesh::File::Token&)
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note:   no known conversion for argument 1 from âconst char [15]â to âconst CADMesh::File::Token&â
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note: candidate: CADMesh::File::Token::Token(CADMesh::File::Token&&)
/nfs/erl/online/user/jgp98/CADMesh/include/Lexer.hh:27:8: note:   no known conversion for argument 1 from âconst char [15]â to âCADMesh::File::Token&&â
In file included from /nfs/erl/online/user/jgp98/CADMesh/include/STLReader.hh:5:0,
                 from /nfs/erl/online/user/jgp98/CADMesh/src/BuiltInReader.cc:4:
/nfs/erl/online/user/jgp98/CADMesh/include/LexerMacros.hh:3:45: error: no matching function for call to âCADMesh::File::Token::Token(<brace-enclosed initializer list>)â
     static Token name##Token{ #name "Token" }; \
                                             ^

Along with a handful of other error messages related to Token/ErrorToken. Does anyone have any guidance?

**Comment by bnara** [comment]
Try running
```
$ make VERBOSE=1
```
and see whether `cmake` is setting compiler flag `-std=c++11`.  If so, then try adding the following line to `CMakeLists.txt`:
```
set(CMAKE_CXX_STANDARD 14)
```

**Comment by bnara** [comment]
Also, I think you are still on master?  Branch v1.1 doesn't have source files `Lexer.hh`, `BuiltInReader.cc`, etc.  You probably don't want to use v1.1 anyway.  It uses `Assimp::Importer` instances that go out of context, taking their imported data with them.  This can create some subtle non-deterministic Heisenbug behavior.

**Comment by fzeiser** [comment]
I think I ran into the same error running on commit 035e857b3562906ee2e29afaa6be5cbcebdb9da4. I paste it here again, as the previous comment had a bad formatting:
```
[ 34%] Completed 'tetgen_external'
[ 42%] Built target tetgen_external
[ 44%] Building CXX object CMakeFiles/cadmesh.dir/src/BuiltInReader.cc.o
In file included from /home/fabiobz/progs/CADMesh/include/BuiltInReader.hh:5:0,
                 from /home/fabiobz/progs/CADMesh/src/BuiltInReader.cc:3:
/home/fabiobz/progs/CADMesh/include/Lexer.hh:34:39: error: no matching function for call to 'CADMesh::File::Token::Token(<brace-enclosed initializer list>)'
 static Token ErrorToken{ "ErrorToken" };
                                       ^
/home/fabiobz/progs/CADMesh/include/Lexer.hh:27:8: note: candidate: constexpr CADMesh::File::Token::Token()
 struct Token
        ^~~~~
/home/fabiobz/progs/CADMesh/include/Lexer.hh:27:8: note:   candidate expects 0 arguments, 1 provided
/home/fabiobz/progs/CADMesh/include/Lexer.hh:27:8: note: candidate: CADMesh::File::Token::Token(const CADMesh::File::Token&)
/home/fabiobz/progs/CADMesh/include/Lexer.hh:27:8: note:   no known conversion for argument 1 from 'const char [11]' to 'const CADMesh::File::Token&'
/home/fabiobz/progs/CADMesh/include/Lexer.hh:27:8: note: candidate: CADMesh::File::Token::Token(CADMesh::File::Token&&)
/home/fabiobz/progs/CADMesh/include/Lexer.hh:27:8: note:   no known conversion for argument 1 from 'const char [11]' to 'CADMesh::File::Token&&'
[...]
```

As suggested, I changed `-std=c++11 ` in  following line
https://github.com/christopherpoole/CADMesh/blob/035e857b3562906ee2e29afaa6be5cbcebdb9da4/CMakeLists.txt#L5

to `-std=c++14`. I also added this line directly `set(CMAKE_CXX_STANDARD 14)
`

This * seemed*  to fix the original error, although I now get stuck with this one (although `libexpat` is installed ) 
```
[ 94%] Building CXX object examples/basic/CMakeFiles/cadmesh_example.dir/src/PrimaryGeneratorAction.cc.o
[ 97%] Linking CXX executable cadmesh_template
/home/fabiobz/miniconda3/envs/myenv/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lexpat
```
